#设置页面url显示项目名
server:
  context-path: /tee
# 数据源基础配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teachereval
    username: root
    password:
    # 连接池配置
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
  jpa:
    database: mysql
  thymeleaf:
    #自动跟新视图缓存
    cache: false
    #弱语法检验
    mode: LEGACYHTML5

#mybatis设置
mybatis:
  mapper-locations: classpath*:mapper/*.xml

mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count\=countSql

Mybar:
  roleList:
    - role: 学生
      right: 0.3
      exerciseList:
        - name: 概念的讲解
          value: 0.15
        - name: 重点和难点
          value: 0.15
        - name: 逻辑性和条理性
          value: 0.1
        - name: 趣味性和生动性
          value: 0.1
        - name: 板书
          value: 0.05
        - name: 辅导（阅读指导）
          value: 0.08
        - name: 作业与批改
          value: 0.1
        - name: 能力培养
          value: 0.1
        - name: 教书育人
          value: 0.1
        - name: 为人师表
          value: 0.07
      answerList:
        - name: 概念的讲解
          A: 语言精练，深入浅出，讲解准确
          B: 讲解清晰，容易接受
          C: 讲解基本准确，但不易接受
          D: 概念紊乱，时有差错
        - name: 重点和难点
          A: 重点突出，讲清难点，举一反三
          B: 能把握重点、难点，但讲解不够明确
          C: 重点不明显，难点讲不透
          D: 重点一言而过，难点草率了事
        - name: 逻辑性和条理性
          A: 层次分明，融会贯通
          B: 条目较清楚，有分析归纳
          C: 平淡叙述，缺乏连贯性
          D: 杂乱无章，前后矛盾
        - name: 趣味性和生动性
          A: 讲解方法新颖，举例生动，有吸引力
          B: 讲解较熟练，语言通俗
          C: 讲解平淡，语言单调
          D: 讲解生疏，远离课题，语言枯燥
        - name: 板书
          A: 简繁适度，清楚醒目
          B: 条目明白，书写整洁
          C: 布局较差，详略失当
          D: 次序凌乱，书写潦草
        - name: 辅导（阅读指导）
          A: 辅导及时、并指导课外阅读
          B: 定期辅导，并布置课外阅读
          C: 辅导较少
          D: 没有辅导
        - name: 作业与批改
          A: 选题得当，批改及时，注意讲评
          B: 作业适量，批改及时
          C: 作业量时轻时重，批改不够及时
          D: 选题随便，批改马虎
        - name: 能力培养
          A: 思路开阔，鼓励创新，注意能力培养、效果明显
          B: 注意学生能力培养，并在教学中有所体现
          C: 能提出能力培养的要求，但缺乏具体的办法
          D: 忽视能力培养，单纯灌输书本知识
        - name: 教书育人
          A: 全面关心学生，经常接触学生，亲切、严格
          B: 关心学生的学业，引导学生学好本门课程
          C: 单纯完成上课任务，与同学接触较少
          D: 对学生漠不关心，放任自流
        - name: 为人师表
          A: 严于律己，以身作则，堪称楷模
          B: 举止文明，待人热情
          C: 注意礼貌，待人和气
          D: 要求不严，言谈失当
    - role: 系主任
      right: 0.25
      exerciseList:
        - name: 教学工作量
          value: 0.225
        - name: 社会工作量
          value: 0.045
        - name: 任课班级
          value: 0.03
        - name: 接受任务态度
          value: 0.028
        - name: 授课计划制定
          value: 0.0252
        - name: 教案首页
          value: 0.0504
        - name: 备课余量
          value: 0.0252
        - name: 教学日志手册的填写
          value: 0.0252
        - name: 教学表格的填写
          value: 0.0252
        - name: 辅导
          value: 0.0504
        - name: 教学秩序的掌握
          value: 0.0504
        - name: 职称
          value: 0.0105
        - name: 运用新知识、新技术能力
          value: 0.042
        - name: 论文撰写、教材编写能力
          value: 0.0525
        - name: 完成任务情况
          value: 0.035
        - name: 教学水平变化
          value: 0.035
        - name: 教学反映
          value: 0.105
        - name: 能力培养
          value: 0.07
        - name: 汲取新信息新技术
          value: 0.035
        - name: 考试命题
          value: 0.035
      answerList:
        - name: 教学工作量
          A: 超工作量
          B: 满工作量
          C: 接近完成（70%）
          D: 差距较大
    - role: 教研组主任
      right: 0.2
      exerciseList:
        - name: 概念的讲解
          value: 0.09
        - name: 重点和难点
          value: 0.09
        - name: 逻辑性、条理性
          value: 0.06
        - name: 趣味性、生动性
          value: 0.06
        - name: 板书
          value: 0.03
        - name: 能力培养
          value: 0.09
        - name: 理论联系实际
          value: 0.06
        - name: 辅导（阅读指导）
          value: 0.06
        - name: 作业与批改
          value: 0.06
        - name: 接受任务的态度
          value: 0.05
        - name: 汲取新技术
          value: 0.05
        - name: 学术与研究水平
          value: 0.1
        - name: 参加教研活动
          value: 0.2
      answerList:
        - name: 概念的讲解
          A: 语言精练，深入浅出，讲解准确
          B: 讲解清晰，容易接受
          C: 讲解基本准确，但不易接受
          D: 概念紊乱，时有差错
    - role: 领导、督导、同行
      right: 0.15
      exerciseList:
        - name: 组织教学
          value: 0.15
        - name: 教学内容与教学要求
          value: 0.15
        - name: 概念讲解
          value: 0.1
        - name: 重点和难点
          value: 0.1
        - name: 趣味性与生动性
          value: 0.08
        - name: 直观教学与板书
          value: 0.07
        - name: 智力能力的培养
          value: 0.1
        - name: 理论联系实际
          value: 0.1
        - name: 教材处理
          value: 0.15
      answerList:
      - name: 组织教学
        A: 教学组织安排得当，气氛活跃，纪律良好
        B: 注意学生动态，教学有条不紊
        C: 忽视教学步骤，师生双边活动较差
        D: 只顾自己讲，不管学生情况
